### ISSUE TITLE
Dom driver not working in atom package

### ISSUE THREAD

**Issue by AljoschaMeyer** [cyclejs/core#353]
I can't use the DOM driver in an atom package. Importing it causes a crash:

```js
import {makeDOMDriver} from '@cycle/dom';
```

```
Cannot find module 'xstream'

stacktrace...
```
Stacktrace at the bottom of this issue, but it shouldn't matter: Atom complains that xstream hasn't been installed. Which is correct, its neither a dependency in my package.json file, nor is it installed in the node_modules folder.

xstream isn't a dependency of the dom-driver, so why does it crash?

The stacktrace:
```
Error: Cannot find module 'xstream'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/aljoscha/projects/atom-pdfs/node_modules/@cycle/dom/lib/makeDOMDriver.js:3:17)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/aljoscha/projects/atom-pdfs/node_modules/@cycle/dom/lib/index.js:40:23)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/aljoscha/projects/atom-pdfs/lib/pdf-view.js:3:36)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/aljoscha/projects/atom-pdfjs/lib/pdf-model.js:46:38)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
```

**Comment by staltz** [comment]
Yes it is

**Comment by Hypnosphi** [comment]
https://github.com/cyclejs/core/releases/tag/v7.0.0

"For instance, if you install Cycle DOM or Cycle HTTP, you must also install xstream"

**Comment by AljoschaMeyer** [comment]
If installing xstream is necessary anyways, why isn't it a dependency of Cycle DOM? Or rather: what am I missing here?
